// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrwfcjdnokvtudihywhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyd2ZjamRub2t2dHVkaWh5d2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDQzMTMsImV4cCI6MjA3MTY4MDMxM30.iFN4xPvOzsSwKIq7IvMLn4u6V2gIS0SHhC3oyjbZydQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});